### PR TITLE
Hotfix for Audit_log_bronze and NotebookCommands_gold

### LINKED ISSUE #1066: [Bug] - Getting null notebook_id in notebookCommands_gold
Customer is getting null notebook_id in notebookCommands_gold.

### LINKED ISSUE #1067: [Bug] - auditLog_Bronze is failing when extra columns are being sent from event hub.
Currently we are taking all the field from properties schema from eventHub. But due to some configuration if we are getting some extra field in this schema then audit log bronze is failing.

### PR DESCRIPTION
**Pull request by souravbaner-da**
Close #1066 
Close #1067

### CODE REVIEW

File: src/main/scala/com/databricks/labs/overwatch/pipeline/BronzeTransforms.scala [hunk 1]
```diff
@@ -349,8 +350,18 @@ trait BronzeTransforms extends SparkSessionWrapper {
...
+          "properties.actionName",
+          "properties.logId",
+          "properties.requestId",
+          "properties.requestParams",
+          "properties.response",
+          "properties.serviceName",
+          "properties.sessionId",
+          "properties.sourceIPAddress",
+          "properties.userAgent")
+        .drop("properties")
```
Comment (aman-db) [inline src/main/scala/com/databricks/labs/overwatch/pipeline/BronzeTransforms.scala:364]: Can we add these column list in Schema.scala and then use this list instead of passing the hardcoded column names ?

File: src/main/scala/com/databricks/labs/overwatch/pipeline/BronzeTransforms.scala [hunk 2]
```diff
@@ -363,15 +374,28 @@ trait BronzeTransforms extends SparkSessionWrapper {
...
```
Comment (aman-db) [inline src/main/scala/com/databricks/labs/overwatch/pipeline/BronzeTransforms.scala:388]: Can we add these column list in Schema.scala and then use this list instead of passing the hardcoded column names ?

File: src/main/scala/com/databricks/labs/overwatch/pipeline/Gold.scala [hunk 3]
```diff
@@ -310,7 +310,7 @@ class Gold(_workspace: Workspace, _database: Database, _config: Config)
   lazy private val appendNotebookCommandsFactProcess: () => ETLDefinition = {
     () =>
       ETLDefinition(
-        BronzeTargets.auditLogsTarget.asIncrementalDF(notebookCommandsFactModule, BronzeTargets.auditLogsTarget.incrementalColumns,1),
+        BronzeTargets.auditLogsTarget.asIncrementalDF(notebookCommandsFactModule, BronzeTargets.auditLogsTarget.incrementalColumns,30),
```
Comment (gueniai) [inline src/main/scala/com/databricks/labs/overwatch/pipeline/Gold.scala:313]: How does this affect the performance of this table? There are potentially many rows in Audit logs that would be brought in when using a 30 day lag
