### PR TITLE
notebook_commands is failing when verbose Audit Logging is not enabled in workspace

### LINKED ISSUE #1033: [BUG] notebook_commands is failing when verbose Audit Logging is not enabled in workspace.

### PR DESCRIPTION
**Pull request by souravbaner-da**
Hot fix for notebookCommands_gold when verbose audit logging is not enabled.

Close #1033

### CODE REVIEW

File: src/main/scala/com/databricks/labs/overwatch/pipeline/GoldTransforms.scala [hunk 1]
```diff
@@ -499,122 +501,132 @@ trait GoldTransforms extends SparkSessionWrapper {
...
+        .lookupWhen(
+          notebookLookupTSDF,
+          maxLookAhead = 100
+        )
+        .df
+        .withColumn("dbu_cost_ps", col("total_DBU_cost") / col("uptime_in_state_H") / lit(3600))
+        .withColumn("estimated_dbu_cost", col("executionTime") * col("dbu_cost_ps"))
+        .drop("cluster_id")
+      notebookCodeAndMetaDF.select(colNames: _*)
+    } else{
```
Comment (gueniai) [inline src/main/scala/com/databricks/labs/overwatch/pipeline/GoldTransforms.scala:624]: Please move the else case to the beginning and handle the error case before the positive case, otherwise it's a bit hard to get to the else 100+ lines after

File: src/main/scala/com/databricks/labs/overwatch/pipeline/GoldTransforms.scala [hunk 2]
```diff
@@ -499,122 +501,132 @@ trait GoldTransforms extends SparkSessionWrapper {
...
+      logger.info("Verbose Audit Log not enabled in workspace")
+      throw new VerboseAuditLoggingDisabled(s"Verbose Audit Logging is not enabled in the workspace. To get the data in notebookCommands_gold it is necessary you " +
```
Comment (gueniai) [inline src/main/scala/com/databricks/labs/overwatch/pipeline/GoldTransforms.scala:626]: In this message, let's also tell them they can exclude the scope in the config if they don't want to use it?

**Review by gueniai — CHANGES_REQUESTED** [review]
Not sure if this is ready for a CR, but just 2 thoughts on what I saw

File: src/main/scala/com/databricks/labs/overwatch/pipeline/GoldTransforms.scala (hunk 1 above)
Comment (souravbaner-da) [reply src/main/scala/com/databricks/labs/overwatch/pipeline/GoldTransforms.scala]: Done

File: src/main/scala/com/databricks/labs/overwatch/pipeline/GoldTransforms.scala (hunk 2 above)
Comment (souravbaner-da) [reply src/main/scala/com/databricks/labs/overwatch/pipeline/GoldTransforms.scala]: Done

File: src/main/scala/com/databricks/labs/overwatch/pipeline/GoldTransforms.scala [hunk 3]
```diff
@@ -490,131 +492,137 @@ trait GoldTransforms extends SparkSessionWrapper {
...
+          maxLookAhead = 100
+        )
+        .df
+        .withColumn("dbu_cost_ps", col("total_DBU_cost") / col("uptime_in_state_H") / lit(3600))
+        .withColumn("estimated_dbu_cost", col("executionTime") * col("dbu_cost_ps"))
+        .drop("cluster_id")
+      notebookCodeAndMetaDF.select(colNames: _*)
+    }else{
+      println("Verbose Audit Log not enabled in workspace")
+      throw new VerboseAuditLoggingDisabled(s"Verbose Audit Logging is not enabled in the workspace. To get the data in notebookCommands_gold it is necessary you " +
```
Comment (gueniai) [inline src/main/scala/com/databricks/labs/overwatch/pipeline/GoldTransforms.scala:623]: Can we use ModuleDisabled instead of defining a new Exception wrapper, in order to be consistent?

File: src/main/scala/com/databricks/labs/overwatch/pipeline/Module.scala [hunk 4]
```diff
@@ -398,6 +398,9 @@ class Module(
         fail(failMsg)
       case e: ModuleDisabled =>
         fail(e.getMessage)
+      case e: VerboseAuditLoggingDisabled =>
+        println("Verbose AUdit Log Disabled")
```
Comment (gueniai) [inline src/main/scala/com/databricks/labs/overwatch/pipeline/Module.scala:402]: Audit instead of AUdit

**Review by gueniai — CHANGES_REQUESTED** [review]

File: src/main/scala/com/databricks/labs/overwatch/pipeline/GoldTransforms.scala (hunk 3 above)
Comment (souravbaner-da) [reply src/main/scala/com/databricks/labs/overwatch/pipeline/GoldTransforms.scala:623]: @gueniai  Done

**Review by gueniai — APPROVED** [review]
