### PR TITLE
Gracefully Handle Exception for NotebookCommands_Gold

### LINKED ISSUE #1094: [Bug] - Handle No Data Exception Gracefully for NotebookCommands_Gold

### PR DESCRIPTION
**Pull request by souravbaner-da**
Close #1094

### CODE REVIEW

File: src/main/scala/com/databricks/labs/overwatch/pipeline/GoldTransforms.scala [hunk 1]
```diff
@@ -499,18 +499,27 @@ trait GoldTransforms extends SparkSessionWrapper {
...
       val notebookLookupTSDF = notebook.asDF
         .select("organization_id", "notebook_id", "notebook_path", "notebook_name", "unixTimeMS", "date")
         .withColumnRenamed("notebook_id", "notebookId")
         .filter('notebookId.isNotNull)
         .distinct
         .toTSDF("unixTimeMS", "organization_id", "date", "notebookId")
 
+      if (clsfIncrementalDF.isEmpty) {
+        throw new NoNewDataException("No New Data", Level.WARN, true)
+      }
```
Comment (sriram251-code) [inline src/main/scala/com/databricks/labs/overwatch/pipeline/GoldTransforms.scala:522]: Please add all the empty check in the beginning of the function.I suggest create a function to check the No new data exception and call that function in the beginning.

Comment (souravbaner-da) [reply src/main/scala/com/databricks/labs/overwatch/pipeline/GoldTransforms.scala]: Done

**Review by sriram251-code — APPROVED** [review]

**Review by gueniai — APPROVED** [review]
LGTM!
