### PR TITLE
Upgrade bug fixed

### LINKED ISSUE #321: Azure - Upgrade 0506 -> 060[3,4] directly -- STEP 10: error rebuilding silver targets
The issue is that a new parameter was introduced into the config in version 0603 and was not properly added to the upgrade path causing a failure.

### PR DESCRIPTION
**Pull request by GeekSheikh**
closes #321

### CODE REVIEW

File: src/main/scala/com/databricks/labs/overwatch/utils/Upgrade.scala [hunk 1]
```diff
@@ -310,29 +310,32 @@ object Upgrade extends SparkSessionWrapper {
...
-    )
-
     val overwatchParamsCols = Array("auditLogConfig", "tokenSecret", "dataTarget", "badRecordsPath", "overwatchScope",
       "maxDaysToLoad", "databricksContractPrices", "primordialDateString", "intelligentScaling", "workspace_name",
       "externalizeOptimize")
 
     // Necessary because if recovering pipeline upgrade the columns may or may not exist so both scenarios
     // must be handled. This ensures both columns are present and present only once
-    val orgRunDetailsBase = spark.read.format("delta").load(pipelineReportPath)
+    val orgRunDetailsBase = spark.read.format("delta").load("/mnt/overwatch_global/05x/global_share/pipeline_report")
```
Comment (alexott) [inline src/main/scala/com/databricks/labs/overwatch/utils/Upgrade.scala:322]: Is it correct to hardcore path?

**Review by alexott — CHANGES_REQUESTED** [review]

File: src/main/scala/com/databricks/labs/overwatch/utils/Upgrade.scala (hunk 1 above)
Comment (GeekSheikh) [reply src/main/scala/com/databricks/labs/overwatch/utils/Upgrade.scala:322]: nope that's a booboo. Customer noticed too lol dangit.

**Review by alexott — APPROVED** [review]
